### ISSUE TITLE
Force Close after starting Watch App after installation

### ISSUE THREAD

**Issue by ghost** [manni-app/manni-ios#2]
## Information

Version: 4.2
Device: Apple Watch 4 GPS
watchOS Version: 5.1.3 (16S535)

## Actual Behavior

After installing the watch app, when the app is started for the first time and access to location services is granted, the icon for "looking for stops" is shown. After a few seconds, the app force closes.

**Comment by PhilippMatthes** [comment]
@clemensbartz thanks for opening this issue! I am unfortunately aware of this issue. It was introduced with the release of WatchOS 4.0. The reason is the same as for #3. Some part of the animation or the stop section causes internal memory leaks. Unfortunately, this is really hard to debug and I already spent many hours investigating this, because even with the debugger attached, the app crashes without linking the debugger to the erroneous code line. I already opened a bug report, but no effort on Apple's side was ever shown to resolve this issue.
Looking into the logs on my real iOS/watchOS device, I found out that the reason for this crash is `Crossed high watermark`, which basically means that some part of memory was overridden, where it shouldn't have been. It seems like some odd part of internal memory management has changed in watchOS 4.0 which yields this crash. 
In investigation of the memory leak I found out that especially the animation caused high memory consumption, where it shouldn't have caused them. In the end, I'll probably completely redesign the watchOS app and just hope that this problem fixes itself.

**Comment by PhilippMatthes** [comment]
I should note that the simulator runs the app perfectly fine. It's the real device that crashes.

**Comment by PhilippMatthes** [comment]
Here's a crash report
```
Incident Identifier: 70A71F8B-084F-4FDA-98A0-2010141C871C
CrashReporter Key:   43df0f342a9ca61e1265bb274bee2e50fb39d88e
Hardware Model:      Watch3,4
Process:             manni-watch Extension [818]
Path:                /private/var/containers/Bundle/Application/1684E692-BA95-4E6F-93B4-14C8CAC563F4/manni-watch.app/PlugIns/manni-watch Extension.appex/manni-watch Extension
Identifier:          com.philippmatthes.manni.watchkitapp.watchkitextension
Version:             16 (2.4.1)
Code Type:           ARM (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           com.philippmatthes.manni.watchkitapp.watchkitextension [361]


Date/Time:           2018-12-17 20:45:02.9382 +0100
Launch Time:         2018-12-17 20:44:52.0000 +0100
OS Version:          Watch OS 5.1.2 (16S5046a)
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_RESOURCE
Exception Subtype: MEMORY
Exception Message: (Limit 50 MB) Crossed High Water Mark
Termination Reason: Namespace JETSAM, Code 0x7
Triggered by Thread:  6

[...]

Thread 6 name:  Dispatch queue: com.apple.root.user-interactive-qos
Thread 6 Attributed:
0   libsystem_platform.dylib      	0x1ac94540 0x1ac8e000 + 25920
1   ....asan_watchos_dynamic.dylib	0x00888cf2 0x880000 + 36082
2   ....asan_watchos_dynamic.dylib	0x00885284 0x880000 + 21124
3   ....asan_watchos_dynamic.dylib	0x008bf042 0x880000 + 258114
4   libcompression.dylib          	0x1cd1a0ce 0x1cd16000 + 16590
5   CoreUI                        	0x2179895a 0x21722000 + 485722
6   CoreUI                        	0x2176a91e 0x21722000 + 297246
7   libdispatch.dylib             	0x1aadb66c 0x1aad6000 + 22124
8   libdispatch.dylib             	0x1aaea9e4 0x1aad6000 + 84452
9   libdispatch.dylib             	0x1aadb648 0x1aad6000 + 22088
10  libdispatch.dylib             	0x1aae8efc 0x1aad6000 + 77564
11  libdispatch.dylib             	0x1aae9588 0x1aad6000 + 79240
12  libsystem_pthread.dylib       	0x1ac9b3e0 0x1ac96000 + 21472
13  libsystem_pthread.dylib       	0x1aca0738 0x1ac96000 + 42808

Thread 6 crashed with ARM Thread State (32-bit):
    r0: 0x416b1900    r1: 0x000000fd      r2: 0x00041723      r3: 0x00020f93
    r4: 0x0b58c800    r5: 0x0b58c7f0      r6: 0x0104de90      r7: 0x193579c8
    r8: 0x00907640    r9: 0x00b3d988     r10: 0x0000001e     r11: 0x07580000
    ip: 0x416d1ff0    sp: 0x193579c8      lr: 0x00000000      pc: 0x1ac94540
  cpsr: 0x20000010
```

**Comment by PhilippMatthes** [comment]
I'll re-symbolicate this crash report now.

**Comment by PhilippMatthes** [comment]
~~Side-note: For no apparent reason, my watchOS app is currently working on my real device.~~
~~Edit: No, it's still randomly crashing.~~
2nd Edit: After attaching the debugger, the watchOS app runs perfectly fine.

**Comment by PhilippMatthes** [comment]
After re-symbolicating, I am almost certain that this issue is dedicated to an internal UI trigger. Adding the wontfix label for now. This issue might be reopened when further information suggesting error on my side is available.
